# Generated by Django 3.0.7 on 2020-06-11 01:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(blank=True, max_length=50)),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('año_nacimiento', models.SmallIntegerField(default=0)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('carrera_origen', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estado_actual', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_asignatura', models.SmallIntegerField(default=0)),
                ('glosa', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora', models.SmallIntegerField(default=0)),
                ('interes', models.BooleanField(default=False)),
                ('medio_contacto', models.CharField(max_length=40)),
                ('autogestion', models.BooleanField(default=True)),
                ('nombre_contacto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora', models.SmallIntegerField(default=0)),
                ('realizacion', models.BooleanField(default=False)),
                ('cumplimiento_objetivos', models.BooleanField(default=False)),
                ('medio_reunion', models.CharField(max_length=50)),
                ('observaciones', models.TextField(default='')),
                ('iniciales_academico', models.CharField(default='', max_length=10)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.SmallIntegerField(default=2010)),
                ('semestre', models.SmallIntegerField(default=1)),
                ('tipo_causal', models.IntegerField(default=0)),
                ('asignaturas_reportadas', models.SmallIntegerField(default=0)),
                ('prioridad', models.SmallIntegerField(default=0)),
                ('observacion', models.CharField(default='', max_length=50)),
                ('reiteraciones_causal', models.SmallIntegerField(default=0)),
                ('tipo_ingreso', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.SmallIntegerField()),
                ('estado', models.CharField(default='', max_length=10)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Reunion')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(blank=True, max_length=50)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('jornada', models.SmallIntegerField(blank=True, null=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Problema_asociado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.SmallIntegerField()),
                ('explicacion', models.TextField(default='')),
                ('estado', models.CharField(default='', max_length=10)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Reunion')),
            ],
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_derivacion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(blank=True, max_length=50)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Administrador')),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Reporte'),
        ),
        migrations.CreateModel(
            name='Causal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.SmallIntegerField(default=2010)),
                ('tipo', models.SmallIntegerField(default=0)),
                ('condiciones', models.TextField(blank=True, null=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Reporte')),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura_reportada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.SmallIntegerField(default=0)),
                ('participacion', models.SmallIntegerField(default=1)),
                ('notas_ponderadas', models.SmallIntegerField(default=1)),
                ('año_semestre', models.IntegerField(default=12010)),
                ('observaciones', models.TextField(blank=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Asignatura')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Reporte')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Profesor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='coordinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Coordinador'),
        ),
    ]
