# Generated by Django 3.0.7 on 2020-06-14 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador'},
        ),
        migrations.AlterModelOptions(
            name='coordinador',
            options={'verbose_name': 'Coordinador'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor'},
        ),
    ]
